fix: migrate from jest to node test and c8
fastify/fastify-passport pull request #1182
Opened 2024-08-04 21:48 UTC by dancastillo

#### Checklist

This PR adds [borp](https://github.com/mcollina/borp) and removes jest

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-08-05 02:35 UTC, climba03003 requested changes
Please keep the `test` inside the root `test` folder.
It shouldn't move inside the `src`.

2024-08-06 07:33 UTC, mcollina commented
You'll need to bump the minimum node.js version. You can do so by increasing the action version to v5 in https://github.com/fastify/fastify-passport/blob/53bb3b79ca78952c5c3d62bf36b252f5e9730f98/.github/workflows/ci.yml#L20.

2024-08-07 01:21 UTC, climba03003 requested changes

2024-08-07 01:21 UTC, climba03003 commented on .github/workflows/ci.yml
> +    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v5
```suggestion
    uses: fastify/workflows/.github/workflows/plugins-ci.yml@v5.0.0
```

2024-08-07 02:45 UTC, climba03003 requested changes

2024-08-07 02:45 UTC, climba03003 commented on tsconfig.json
> +  "include": ["src", "test"]
Please remove the `test` here.
It is used to build the packages, and should not include `test`.

2024-08-07 02:45 UTC, climba03003 commented on tsconfig.test.json
> -{
Revert the removal of this file.

2024-08-07 02:46 UTC, climba03003 commented on package.json
> +  "main": "dist/src/index.js",
Please revert the changes to built path.

2024-08-08 21:27 UTC, gurgunday reviewed
Lint is failing

2024-08-10 17:19 UTC, gurgunday approved these changes

2024-08-14 15:25 UTC, mcollina approved these changes
lgtm

2024-08-18 05:13 UTC, gurgunday approved these changes
Lgtm

2024-09-01 18:56 UTC, dancastillo commented
hey @climba03003 I updated based on your comments could you ptal?

2024-09-01 21:03 UTC, climba03003 approved these changes

2024-09-01 21:29 UTC, gurgunday approved these changes

2024-09-02 07:40 UTC, merged